# Generated by Django 5.1.7 on 2025-04-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
    ]
